<?php


namespace App\Constantes;


class Constantes
{
    const SUCESSO_CREATE_SERVICE = 'SERVIÇO CRIADO COM SUCESSO.';
    const SUCESSO_UPDATE_SERVICE = 'SERVIÇO EDITADO COM SUCESSO.';
    const SUCESSO_DELETE_SERVICE = 'SERVIÇO DELETADO COM SUCESSO.';

    const ERROR_CREATE_SERVICE = 'NÃO FOI POSSÍVEL CRIAR O SERVIÇO.';
    const ERROR_UPDATE_SERVICE = 'NÃO FOI POSSÍVEL EDITAR O SERVIÇO.';
    const ERROR_DELETE_SERVICE = 'NÃO FOI POSSÍVEL DELETAR O SERVIÇO.';


    const SUCESSO_CREATE_ORDER_SERVICE = 'ORDEM DE SERVIÇO CRIADO COM SUCESSO.';
    const SUCESSO_UPDATE_ORDER_SERVICE = 'ORDEM DE SERVIÇO EDITADO COM SUCESSO.';
    const SUCESSO_DELETE_ORDER_SERVICE = 'ORDEM DE SERVIÇO DELETADO COM SUCESSO.';

    const ERROR_CREATE_ORDER_SERVICE = 'NÃO FOI POSSÍVEL CRIAR A ORDEM DE SERVIÇO.';
    const ERROR_UPDATE_ORDER_SERVICE = 'NÃO FOI POSSÍVEL EDITAR A ORDEM DE SERVIÇO.';
    const ERROR_DELETE_ORDER_SERVICE = 'NÃO FOI POSSÍVEL DELETAR A ORDEM DE SERVIÇO.';

    const SUCESSO_UPDATE_PERFIL = 'PERFIL ATUALIZADO COM SUCESSO';
    const ERROR_UPDATE_PERFIL = 'NÃO FOI POSSÍVEL ATUALIZAR O PERFIL';

}
